#!/bin/bash
# ABOUT: Installs R package onto remote server(s)
# KEYWORDS: Install package remote
display_usage() {
	echo -e "Usage: \`basename \$0\` [package name] [Rscript path on remote] [servers...]"
	echo -e "Usage: `basename $0` --help"
  echo "template bash script"
}

# if less than two arguments supplied, display usage
if [  "$#" -eq 3 ] || [ "$1" == "--help" ]; then
	display_usage
	exit 1
fi

PACKAGENAME_ECHO="$1"
RPATH_ECHO="$2"
REMOTES_ECHO="${@:3}"


echo "PACKAGENAME=${PACKAGENAME_ECHO}"
echo "RPATH=${RPATH_ECHO}"
echo "REMOTES=\"${REMOTES_ECHO}\""

cat << EndOfMessage
#!/bin/bash	
# ABOUT: Installs R package onto remote server(s)	
# KEYWORDS: Install package remote	
n=`ls ../${PACKAGENAME}_* 2>/dev/null | wc -l`
if [ "$n" -gt "0" ]; then
        echo "Multiple packages found:"
        ls ../${PACKAGENAME}_*
        exit 1
fi

case "$OSTYPE" in
  *darwin*)
    PACKAGE=`basename ../${PACKAGENAME}_*.tgz`
    ;;
  *linux*)
    PACKAGE=`basename ../${PACKAGENAME}_*.tar.gz`
    ;;
esac

for REMOTE in ${REMOTES}
do
        ssh $REMOTE "rm /tmp/${PACKAGENAME}_*"
        ssh $REMOTE "echo 'remove.packages(\"${PACKAGENAME}\");'> /tmp/remove${PACKAGENAME}.R; ${RPATH} /tmp/remove${PACKAGENAME}.R"
       scp ../${PACKAGE} $REMOTE:/tmp
       ssh $REMOTE "echo 'install.packages(\"/tmp/$PACKAGE\",type=\"source\",repos=NULL)' > /tmp/install${PACKAGENAME}.R; ${RPATH} /tmp/install${PACKAGENAME}.R"
done
EndOfMessage
