#!/bin/bash
# ABOUT:
# KEYWORDS:
display_usage() {
	echo -e "Usage: `basename $0` [file1.markdown] [file2.markdown] ... "
}

# if less than two arguments supplied, display usage
if [  $# -lt 1 ]; then
	display_usage
	exit 1
fi

for i in "$@"
do 
	pandoc -f markdown $i > "${i%.markdown}.html"
	sed -i 's/\.markdown/.html/' "${i%.markdown}.html"
	sed -i 's#<a href="README.html">Markdown</a>#<a href="README.markdown">Markdown</a>#g' "${i%.markdown}.html" > /dev/null
done

