#!/bin/bash
# ABOUT: Print a bash template to stdout. Use redirect to create a file
# KEYWORDS: bash template usage
cat << EndOfMessage
#!/bin/bash
# ABOUT:
# KEYWORDS:
display_usage() {
	echo -e "Usage: \`basename \$0\` [arguments]"
	echo -e "Usage: `basename $0` --help"
  echo "template bash script"
}

# if less than two arguments supplied, display usage
if [  \$# -ge 0 ] || [ "\$1" == "--help" ]; then
	display_usage
	exit 1
fi

# Colored logging
function info() {
	GREEN='\033[0;32m'
	NC='\033[0m' # No Color
	printf "\${GREEN}INFO: \${1}\${NC}\n"
}
function warn() {
	YELLOW='\033[1;33m'
	NC='\033[0m' # No Color
	printf "\${YELLOW}WARNING: \${1}\${NC}\n"
}
function fatal() {
	RED='\033[0;31m'
	NC='\033[0m' # No Color
	printf "\${RED}FATAL: \${1}\${NC}\n"
	exit 1
}

info "info msg"
warn "warn msg"
fatal "fatal msg"


EndOfMessage
